### ISSUE TITLE
demos missing

### ISSUE THREAD

**Issue by dalu** [frekele/oracle-java#2]
Yes, I know. Who needs demos, right?
Well gentoo does...
The ebuild requires 

jdk-8u212-linux-x64-demos.tar.gz

do you think it's possible to provide those?

**Comment by frekele** [comment]
@dalu , i do not mean to.

This repository is exclusively for compiling the docker-java container for use in development and test.

You should not use external means to obtain the files that oracle provides. It is important for you to know that the license for upgrade versions above jdk 8u202 can only be for development and testing purposes, it can not be used commercially.

You should do as everyone does, login with your oracle account and access the url: https://www.oracle.com/technetwork/java/javase/downloads/index.html to download what you need.

**Comment by frekele** [comment]
@dalu, I do not intend to provide.

This repository is exclusively for compiling the docker-java container for use in development and test.

You should not use external means to obtain the files that oracle provides. It is important for you to know that the license for upgrade versions above jdk 8u202 can only be for development and testing purposes, it can not be used commercially.

You should do as everyone does, login with your oracle account and access the url: https://www.oracle.com/technetwork/java/javase/downloads/index.html to download what you need.
